name: CI
on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.1' ]
        container:
            image: jakzal/phpqa:php8.1
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: xdebug

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

#            - name: PHP Coding Standards
#              run: |
#                  php-cs-fixer fix ./src --dry-run --rules=@Symfony --verbose
#                  phpstan analyse ./src -l3
#                  phpdd ./src
#                  phpcpd ./src --exclude './src/Controller/Admin/' --exclude './src/Entity'
#              continue-on-error: true