name: CI
on: [push]

jobs:
    build:
        name: Continuous Integration
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.1' ]
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                ports:
                    - "5432:5432"
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  coverage: xdebug

            - name: Get composer cache directory
              id: composer-cache
              run: echo "DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ env.DIR }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Symfony CLI
              run: |
                  curl -sS https://get.symfony.com/cli/installer | bash
                  mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

            - name: PHPStan
              uses: docker://jakzal/phpqa:php8.1
              with:
                  args: phpstan analyze src/ -l3

            - name: PHP-CS-Fixer
              uses: docker://jakzal/phpqa:php8.1
              with:
                  args: php-cs-fixer fix src/ --dry-run --rules=@Symfony --verbose
